# permissions for end users to edit jskinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jskind-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: js-project
    app.kubernetes.io/part-of: js-project
    app.kubernetes.io/managed-by: kustomize
  name: jskind-editor-role
rules:
- apiGroups:
  - js-group.js.domain
  resources:
  - jskinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - js-group.js.domain
  resources:
  - jskinds/status
  verbs:
  - get
