---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - js-group.js.domain
  resources:
  - jskinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - js-group.js.domain
  resources:
  - jskinds/finalizers
  verbs:
  - update
- apiGroups:
  - js-group.js.domain
  resources:
  - jskinds/status
  verbs:
  - get
  - patch
  - update
